[package]
name = "tgtracker"
version = "0.1.0-alpha"
authors = ["Scalar Waves <scalarwaves@null.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/tonal-glyph/tgtracker.git"

[[bin]]
name = "tgtracker"
path = "src/main.rs"

[dependencies]
# azul = "0.1.0"
daggy = "0.6.0"
rand = "0.5.5"
conrod = "0.61"
conrod_derive = "*"
dsp-chain = "0.13"
find_folder = "*"
nannou = "0.8.0"
petgraph = "0.4"
rusttype = "*"
sample = "0.10.0"
state = "0.4.1"
# pcm-flow = "0.5.0"
# rutie = "0.5.0"
