[package]
name = "tgtracker"
version = "0.1.0-alpha"
authors = ["Scalar Waves <scalarwaves@null.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/tonal-glyph/tgtracker.git"

[[bin]]
name = "tgtracker"
path = "src/main.rs"

[dependencies]
daggy = "0.6.0"
conrod_derive = "0.1.2"
rand = "0.5.5"
conrod = "0.61"
dsp-chain = "0.13"
nannou = "0.8.0"
petgraph = "0.4"
ttf-noto-sans = "0.1.1"
rusttype = "0.7.3"
#sample = "0.10.0"
#pcm-flow = "0.5.0"
#rutie = "0.5.0"
