[package]
name = "tgtracker"
version = "0.0.0-alpha"
authors = ["Lawrence Dark <darklawrence0@gmail.com>"]

[[bin]]
name = "tgtracker"
path = "src/main.rs"

[dependencies]
config = "0.8.0"
gluon = "0.7.1"
itertools = "0.7.8"
libc = "0.2.41"
memmap = "0.6.2"
winit = "0.15.0"
walkdir = "2.1.4"