[package]
name = "tgtracker"
version = "0.1.0-alpha"
authors = [
    "Andrew Prentice <scalarwaves@null.net>",
    "Micah Johnston <micah@glowcoil.com>"
]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/tonal-glyph/tgtracker.git"

[[bin]]
name = "tgtracker"
path = "src/main.rs"

[dependencies]
dsp-chain = "0.13.1"  #digital signal processing graphs
glyph_brush = "0.4.1"  #text rendering, reexports rusttype
lyon = "0.13.1"  #SVG-compatible path tesselator
nannou = "0.8.0"  #reexports conrod, cpal, glium, find_folder
sdl2 = "0.32.1" #hardware abstraction
stretch = "0.1.12" #flexbox implementation
